# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
b = b[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
# Random Integer values
n = np.arange(0,9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
c = [1,2,0,0,4,0]
np.nonzero(c)

(array([0, 1, 4], dtype=int64),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [21]:
# Randome decimal numbers
np.random.rand(3,3,3)

array([[[0.36865748, 0.77227503, 0.78423876],
        [0.37115357, 0.87499925, 0.73422961],
        [0.90165736, 0.24343692, 0.09198647]],

       [[0.83799531, 0.78373191, 0.90729689],
        [0.44134225, 0.94951201, 0.16264195],
        [0.04619565, 0.69872104, 0.23302814]],

       [[0.18464396, 0.21679429, 0.47074502],
        [0.40985948, 0.51610045, 0.66158615],
        [0.30328223, 0.07119528, 0.84057684]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
# Random Integer values
h= np.random.randint(25, size=(10,10))
print(h)
np.min(h)

[[ 8  0  8 20 20 15  6 22  8 21]
 [ 0  7 15  4 16  1 17  3 20 17]
 [ 2 23  4  6 17  0 17 14 16 10]
 [11 11  4 18 13 20  8  0 12 12]
 [17  5 18  8 10  4 15 24 22 17]
 [10  2 16 17  5 13 21 21 20  1]
 [23 19 14 19 18 18 20  7 17 21]
 [18  4 22  6 23 20 14 20 16  4]
 [16  1 16  4 24 15 23 16 21  1]
 [ 2  8 24 10  3  0 19 19  9 16]]


0

In [26]:
np.max(h)

24

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
x = np.random.random(30)
print(x)
np.mean(x)

[0.48740282 0.1153183  0.09509365 0.93048919 0.90334253 0.12511477
 0.39624766 0.66488383 0.52053613 0.46632151 0.93973972 0.07526575
 0.00617304 0.93159929 0.84236033 0.56625911 0.02010493 0.00953553
 0.44293224 0.51082908 0.03752864 0.64725246 0.89009328 0.60903325
 0.15692371 0.56631611 0.35328479 0.33365955 0.12137797 0.2207959 ]


0.43286050142818344

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
output[1:4, 1:-1] = z

print(z)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
output2 = np.zeros((7,7))
print(output2)

output2[1:6, 1:-1] = output
print(output2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
0 * np.nan

nan

In [41]:
np.nan == np.nan

False

In [42]:
np.inf > np.nan

False

In [43]:
np.nan - np.nan

nan

In [44]:
np.nan in set([np.nan])

True

In [45]:
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [47]:
p = np.diag([1,2,3,4,5])
print(p)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [49]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.62762768 0.24083081 0.34852817 1.         0.74648508]
 [0.         0.07753477 0.10074698 0.15843551 0.93838779]
 [0.35083373 0.38118878 0.22275326 0.33520894 0.65103405]
 [0.26264747 0.16911281 0.09951453 0.77461329 0.12332258]
 [0.65855785 0.87279688 0.64297175 0.75160161 0.80318902]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
Z = np.arange(11)
Z
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 18. How to round away from zero a float array ? (★☆☆)

In [52]:
def round_array(x,y):
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

[32. 52.  0.]


#### 19. Find common values between two arrays? (★☆☆)

In [53]:
  
ar1 = np.array([12, 14, 15, 16, 17])
ar2 = np.array([2, 4, 5, 6, 7, 8, 9, 12])
  
# Common values between two arrays
print(np.intersect1d(ar1, ar2))

[12]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\AppData\Local\Temp/ipykernel_15632/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [55]:
def generate(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [56]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [57]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.1032186  0.11101857 0.15212728 0.17867528 0.23980504 0.48984559
 0.50903691 0.58843671 0.81409808 0.88738464]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [58]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [59]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.94065319 0.72070832 0.64167064 0.         0.44196576 0.84287458
 0.1620913  0.25742319 0.11746939 0.37162476]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [60]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4949935708236135


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [62]:
float_array = np.array([[1, 2.3],[3.5, 4.7]])
print(float_array)

int_array = float_array.astype(int)
print(int_array)

[[1.  2.3]
 [3.5 4.7]]
[[1 2]
 [3 4]]


#### 28. Sort an array by the nth column? (★★☆)

In [63]:
a = np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
a = a[a[:,1].argsort()] 
print(a)

[[7 0 5]
 [9 2 3]
 [4 5 6]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [64]:
print("Original array:")
nums = np.random.randint(0,3,(4,10))
print(nums)
print("\nTest whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

Original array:
[[1 1 1 1 2 0 2 1 2 0]
 [1 0 1 2 0 0 2 2 1 1]
 [2 2 2 2 0 2 1 0 0 2]
 [0 1 1 0 0 1 1 1 0 0]]

Test whether the said array has null columns or not:
False


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [65]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [66]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [67]:
a1 = ((0, 1, 0, 1))
a = list(a1)
  
for x in range(len(a)):
    if(a[x]):
        a[x] = 0
    else:
        a[x] = 1
  
print(a)

[1, 0, 1, 0]


#### 33. Find the most frequent value in an array?

In [68]:
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


#### 34. Get the n largest values of an array (★★★)

In [71]:
# create numpy 1d-array
arr = np.array([2, 0,  1, 5,
                4, 1, 9])
  
print("Given array:", arr)
  
# sort an array in
# ascending order
  
# np.argsort() return
# array of indices for
# sorted array
sorted_index_array = np.argsort(arr)
  
# sorted array
sorted_array = arr[sorted_index_array]
  
print("Sorted array:", sorted_array)
  
# we want 1 largest value
n = 1
  
# we are using negative
# indexing concept
  
# take n largest value
rslt = sorted_array[-n : ]
  
# show the output
print("{} largest value:".format(n),
      rslt[0])

Given array: [2 0 1 5 4 1 9]
Sorted array: [0 1 1 2 4 5 9]
1 largest value: 9


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [72]:
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
  
print('Original Array :' ,
      arr2D, sep = '\n')
  
# Get unique rows from
# complete 2D-array by 
# passing axis = 0 in 
# unique function along
# with 2D-array
uniqueRows = np.unique(arr2D, 
                       axis = 0)
  
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]
