In [1]:
def sumLargestNumbers(lst):
    # Put your solution here
    max_a = max(lst)
    lst.remove(max_a)
    max_b = max(lst)
    return max_a + max_b


print(sumLargestNumbers([1, 10]))
print(sumLargestNumbers([1, 2, 3]))
print(sumLargestNumbers([10, 4, 34, 6, 92, 2]))

11
5
126


In [2]:
def conditionalSum(values, condition):
    # Your code here
    total = 0
    if condition == "even":
        for i in values:
            if i % 2 == 0:
                total += i
    if condition == "odd":
        for i in values:
            if i % 2 == 1:
                total += i
    return total

print(conditionalSum([1, 2, 3, 4, 5], "even"))
print(conditionalSum([1, 2, 3, 4, 5], "odd"))
print(conditionalSum([13, 88, 12, 44, 99], "even"))
print(conditionalSum([], "odd"))

6
9
144
0


In [9]:
def numberOfVowels(data):
    # Put your solution here
    vowels = ['a', 'e', 'i', 'o', 'u']
    vowel_numbers = 0
    for i in range(len(data)):
        if data[i] in vowels:
            vowel_numbers += 1
    
    return vowel_numbers

            
print(numberOfVowels("orange"))
print(numberOfVowels("lighthouse labs"))
print(numberOfVowels("aeiou"))

3
5
5


In [5]:
len('chorus')

6

In [7]:
vowels = ['a', 'e', 'i', 'o', 'u']
a = 'chorus'
a[2] in vowels

True

In [45]:
def instructorWithLongestName(instructors):
    # Put your solution here
    index = 0
    lst_name = []
    for data in instructors:
        lst_name.append(list(data.values())[0])
        index += 1
    
    index = 0
    len_name = []
    for num in lst_name:
        len_name.append(len(num))
        index += 1
        
    max_value = max(len_name)
    max_index = len_name.index(max_value)
     
    return dict(instructors[max_index].items())
     

print(instructorWithLongestName([
  {"name": "Samuel", "course": "iOS"},
  {"name": "Jeremiah", "course": "Data"},
  {"name": "Ophilia", "course": "Web"},
  {"name": "Donald", "course": "Web"}
]))
print(instructorWithLongestName([
  {"name": "Matthew", "course": "Data"},
  {"name": "David", "course": "iOS"},
  {"name": "Domascus", "course": "Web"}
]))

{'name': 'Jeremiah', 'course': 'Data'}
{'name': 'Domascus', 'course': 'Web'}


In [35]:
d = [
  {"name": "Samuel", "course": "iOS"},
  {"name": "Jeremiah", "course": "Data"},
  {"name": "Ophilia", "course": "Web"},
  {"name": "Donald", "course": "Web"}
]

len(d)
list(d[2].values())[0]

'Ophilia'

In [37]:
dict(d[2].items())

{'name': 'Ophilia', 'course': 'Web'}

In [44]:
index = 0
lst_name = []
for data in d:
    lst_name.append(list(data.values())[0])
    index += 1

print(lst_name)

['Samuel', 'Jeremiah', 'Ophilia', 'Donald']


In [51]:
def urlEncode(text):
    # Put your solution here

    if text[0] == ' ':
        text = text[1:]
    elif text[-1] == ' ':
        text = text[:-1]
    
    text_edited = text.replace("  ", "")
    text_edited = text_edited.replace(" ", "%20")
    
    return text_edited


print(urlEncode("Lighthouse Labs"))
print(urlEncode(" Lighthouse Labs  "))
print(urlEncode("blue is greener than purple for sure"))

Lighthouse%20Labs
Lighthouse%20Labs
blue%20is%20greener%20than%20purple%20for%20sure


In [49]:
words = " me Nicole "
words_t = words.replace(" ", "%20")
print(words_t)

%20me%20Nicole%20


In [142]:
def whereCanIPark(spots, vehicle):
    # Code here!
    index_parking = []
    index_col = 0
    index_row = 0
    for index_row in range(len(spots)):
        if index_parking:
            break
        for i in spots[index_row]:
            if vehicle == 'regular':
                if i == 'R':
                    index_parking.append(index_col)
                    index_parking.append(index_row)
                    print(index_parking)
                    break
                index_col += 1
                if index_col == len(spots[0]):
                    index_col = 0

            if vehicle == 'small':
                if i == 'R' or i == 'S':
                    index_parking.append(index_col)
                    index_parking.append(index_row)
                    print(index_parking)
                    break
                index_col += 1
                if index_col == len(spots[0]):
                    index_col = 0                    
                    
            if vehicle == 'motorcycle':
                if i == 'R' or i == 'S' or i == 'M':
                    index_parking.append(index_col)
                    index_parking.append(index_row)
                    print(index_parking)
                    break
                index_col += 1
                if index_col == len(spots[0]):
                    index_col = 0   
                    
                    
    if not index_parking:
        print(False)
        
        

print(whereCanIPark(
  [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ],
  'regular'
))

print(whereCanIPark(
  [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ],
  'small'
))

print(whereCanIPark(
  [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ],
  'motorcycle'
))

[4, 0]
None
False
None
[3, 1]
None


In [140]:
# regular
nh = [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ]

#nh[0][4]
index_parking = []
index_col = 0
index_row = 0
for index_row in range(len(nh)):
    if index_parking:
        break
    for i in nh[index_col]:
        if i == 'R':
            index_parking.append(index_col)
            index_parking.append(index_row)
            print(index_parking)
            break
        index_col += 1
        if index_col == len(nh[0]):
            index_col = 0

if not index_parking:
    print(False)
    


[4, 0]


In [139]:
# small
nh1 = [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ]

index_parking = []
index_col = 0
index_row = 0

for index_row in range(len(nh1)):
    if index_parking:
        break
    for i in nh1[index_row]:
        if i == 'R' or i == 'S':
            index_parking.append(index_col)
            index_parking.append(index_row)
            print(index_parking)
            break
        index_col += 1
        if index_col == len(nh1[0]):
            index_col = 0


if not index_parking:
    print(False)
    


False


In [138]:
# motorcycle
nh2 = [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ]

index_parking = []
index_col = 0
index_row = 0

for index_row in range(len(nh2)):
    if index_parking:
        break

    for i in nh2[index_row]:
        if i == 'R' or i == 'S' or i == 'M':
            index_parking.append(index_col)
            index_parking.append(index_row)
            print(index_parking)
            break
        index_col += 1    
        if index_col == len(nh2[0]):
            index_col = 0
              

if not index_parking:
    print(False)

[3, 1]


In [134]:
# motorcycle
nh2 = [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ]

nh2[1][3]



'S'

In [148]:
def checkAir(samples, threshold):
    # Code here!
    percent = samples.count('dirty') / len(samples)
    
    if percent < threshold:
        print("Clean")
    else:
        print("Polluted")
    


print(checkAir(
  ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty'],
  0.3
))

print(checkAir(
  ['dirty', 'dirty', 'dirty', 'dirty', 'clean'],
  0.25
))

print(checkAir(
  ['clean', 'dirty', 'clean', 'dirty', 'clean', 'dirty', 'clean'],
  0.9
))


Polluted
None
Polluted
None
Clean
None


In [146]:
air1 = ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty']
len(air1)
air1.count('dirty')
percent = air1.count('dirty') / len(air1)
print(percent)

0.4


In [68]:
def repeatNumbers(data):
    # Put your solution here
    #print(len(data))
    n = 0
    lst = []
    for i in data:
        #print("i: ", i)
        #print("n: ", n)
        if n < len(data)-1:
            for h in range(i[1]):
                lst.append(i[0])
            
            lst.append(", ")
            #print("if statement, lst: ", lst)
        else:
            for m in range(i[1]):
                lst.append(i[0])
             #print("else statement, lst: ", lst)
         
        n += 1
        
    my_lst = ''.join(map(str, lst))
    
    return my_lst

In [69]:
print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))
print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

1111111111
11, 222
10101010, 343434343434, 9292


In [23]:
# https://stackoverflow.com/questions/12453580/how-to-concatenate-items-in-a-list-to-a-single-string
my_lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_lst_str = ''.join(map(str, my_lst))
print(my_lst_str)

12345678910


In [78]:
def camelCase(input):
    # Your code here
    arr_string = input.split(' ', maxsplit=15)
    
    arr_string_rev = []
    for n in range(len(arr_string)):
        if n == 0:
            arr_string_rev.append(arr_string[n])
        else:
            arr_string_rev.append(arr_string[n].capitalize())
    
    return ''.join(map(str, arr_string_rev))

In [79]:
print(camelCase("this is a string"))
print(camelCase("loopy lighthouse"))
print(camelCase("supercalifragalisticexpialidocious"))

thisIsAString
loopyLighthouse
supercalifragalisticexpialidocious


In [71]:
"this is a string".find(' ')

4

In [72]:
string = "this is a string"
string.capitalize()

'This is a string'

In [74]:
lst = 'this is a string'.split(' ', maxsplit=10)
lst

['this', 'is', 'a', 'string']

In [93]:
import numpy as np

In [120]:
def multiplicationTable(maxValue):
    # Your code here
    number = 1
    arr_lst = []
    for row in range(1, maxValue + 1):
        if row == 1:
            for column in range(1, maxValue + 1):
                arr_lst.append(column)
            
            arr_lst = np.asarray(arr_lst)            
            NH = arr_lst
            number += 1

        else:
            arr_new = []
            for column in range(1, maxValue + 1):               
                arr_new.append(column*number)

            arr_new = np.asarray(arr_new)
            NH_new = arr_new
            NH = np.vstack([NH, NH_new])
            number += 1
    
    return NH

# https://stackoverflow.com/questions/3881453/numpy-add-row-to-array

In [121]:
print(multiplicationTable(1))
print(multiplicationTable(5))
print(multiplicationTable(10))

[1]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
